# Generated by Django 5.1.5 on 2025-02-03 21:24

import django.core.validators
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Course',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('name', models.CharField(max_length=255, unique=True, verbose_name='Название курса')),
                ('code', models.CharField(max_length=50, unique=True, verbose_name='Код курса')),
                ('description', models.TextField(blank=True, verbose_name='Описание')),
                ('start_date', models.DateField(verbose_name='Дата начала')),
                ('duration', models.PositiveIntegerField(validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(52)], verbose_name='Продолжительность (недель)')),
                ('instructor', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='courses', to='users.user', verbose_name='Преподаватель')),
            ],
            options={
                'verbose_name_plural': 'Курсы',
                'ordering': ['-start_date'],
            },
        ),
    ]
